-- Supabase migration — V2 qualitative layer.
--
-- ADDITIVE ONLY: extends the (V1-reserved, empty) qualitative_notes table,
-- adds a feed_status reliability table, and a stocks.ir_rss_url column.
-- Touches NOTHING in the scoring path (fundamentals/risk/composite) — the
-- qualitative layer is strictly separate and never fused into composite_score.
--
-- Apply MANUALLY in the Supabase SQL Editor (the app never runs this itself).
-- Every statement is idempotent (IF NOT EXISTS / DROP-then-CREATE) so a
-- re-run is safe.

-- --- qualitative_notes: extend the V1-reserved table --------------------
-- V1 shape (see supabase_schema.sql): id, ticker, note, source_url, created_at.
-- ticker + source_url already exist; everything below is new.
alter table qualitative_notes add column if not exists category    text; -- dated_contract | regulatory_admission | technical_moat | m_and_a
alter table qualitative_notes add column if not exists sentiment   text; -- positive | negative | neutral
alter table qualitative_notes add column if not exists severity    text; -- low | medium | high
alter table qualitative_notes add column if not exists confidence  text; -- high | medium | low
alter table qualitative_notes add column if not exists event_date  date; -- date EXTRACTED from the source text, not the scan date
alter table qualitative_notes add column if not exists source_type text; -- edgar | ir_rss | newsletter | press
alter table qualitative_notes add column if not exists dedup_hash  text; -- SHA-256 of the normalized text (see app/qualitative/dedup.py)
alter table qualitative_notes add column if not exists summary     text; -- short 1-2 sentence summary generated by Groq

-- Dedup guard: at most one note per (ticker, dedup_hash). The orchestrator
-- also checks this in Python before calling Groq, but the unique index is the
-- hard backstop (a concurrent run can't double-insert the same event).
-- NB: rows with dedup_hash IS NULL are not constrained (multiple NULLs allowed),
-- which is fine — every V2-written row carries a hash.
create unique index if not exists idx_qualitative_notes_dedup
    on qualitative_notes (ticker, dedup_hash);

-- Timeline queries hit (ticker, event_date desc) — see GET /api/stocks/{ticker}/qualitative.
create index if not exists idx_qualitative_notes_ticker_event_date
    on qualitative_notes (ticker, event_date desc);

-- --- feed_status: per-(ticker, source) feed reliability -----------------
-- Pattern mirrors refresh_queue: an internal work/status list. Each collector
-- writes here after every run (ok/failed/stale), never fails silently.
create table if not exists feed_status (
    id              bigint generated always as identity primary key,
    ticker          text not null references stocks (ticker) on delete cascade,
    source_type     text not null,  -- edgar | ir_rss | newsletter | press
    feed_url        text,
    status          text not null,  -- ok | failed | stale
    last_success_at timestamptz,
    last_error      text,
    updated_at      timestamptz not null default now(),
    unique (ticker, source_type)
);

create index if not exists idx_feed_status_status
    on feed_status (status, updated_at desc);

-- --- stocks: manually-curated IR RSS feed URL (nullable) ----------------
-- Set via /admin (PATCH /api/stocks/{ticker}); NULL means "no IR feed for
-- this ticker" and the ir_rss collector skips it cleanly.
alter table stocks add column if not exists ir_rss_url text;

-- --- RLS: same policy as the rest ("write local service_role, read anon") -
-- qualitative_notes already has RLS + an "anon read" policy from
-- supabase_schema.sql; the new columns are covered by it automatically
-- (a SELECT policy is column-agnostic), so nothing to change there.
--
-- feed_status is new and must be exposed read-only to anon (the /admin feed
-- monitor reads it via the public API on Render, which holds the anon key).
alter table feed_status enable row level security;
drop policy if exists "anon read feed_status" on feed_status;
create policy "anon read feed_status" on feed_status for select to anon, authenticated using (true);
